### ISSUE TITLE
Install failed using root when following quick start instruction

### ISSUE THREAD

**Issue by dayou5168** [tech-greedy/singularity#103]
**Describe the bug**
Follow the quick start instruction, and get err as bellow

> npm ERR! code 127
> npm ERR! path /root/.nvm/versions/node/v16.16.0/lib/node_modules/@techgreedy/singularity/node_modules/leveldown
> npm ERR! command failed

**Version**
Can't install singularity

**To Reproduce**
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
source ~/.bashrc
nvm install 16
npm i -g @techgreedy/singularity

**Expected behavior**
Install successfully

**Comment by liuziba** [comment]
What's your platform? What's the node version (`nvm list`). Can you try install with `--loglevel verbose` and paste the log here?

**Comment by dayou5168** [comment]
#### platform info
Ubuntu 18.04.6 LTS 
Linux ESXI-4-8 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

#### nvm list output
>->     v16.16.0
         system
default -> 16 (-> v16.16.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v16.16.0) (default)
stable -> 16.16 (-> v16.16.0) (default)
lts/* -> lts/gallium (-> v16.16.0)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.20.0 (-> N/A)
lts/gallium -> v16.16.0

#### log file as bellow
[2022-07-21T02_20_44_288Z-debug-0.log](https://github.com/tech-greedy/singularity/files/9155672/2022-07-21T02_20_44_288Z-debug-0.log)

**Comment by liuziba** [comment]
Could you try this solution?
https://timjrobinson.com/fixing-node-gyp-permission-denied-when-running-as-root/

**Comment by dayou5168** [comment]
#### Didn't fix the problem
[Uploading 2022-07-21T06_43_42_191Z-debug-0.log…]()

**Comment by liuziba** [comment]
This seems to work
```shell
chown -R $(whoami) ~/
npm config set unsafe-perm true
npm config set user 0
```

**Comment by dayou5168** [comment]
It works!  should we update the README file？

**Comment by liuziba** [comment]
Added to README. Thanks for the suggestion.
