### ISSUE TITLE
DealTracking does not keep track of deals that go Active then get slashed

### ISSUE THREAD

**Issue by marshyonline** [tech-greedy/singularity#154]
**Describe the bug**
DealTracking will keep track of deals that are either, proposed or published - the only other time it is checked is on expiry.
But if a deal becomes active on-chain and is then terminated by the SP - it becomes slashed and singularity will not pick up on it due to this line.

https://github.com/tech-greedy/singularity/blob/e0ee07f1b16808c16ceac500adda162b2f16fb35/src/deal-tracking/DealTrackingService.ts#L238

**Expected behavior**
At scale, we don't want to be checking all active deals every time a check runs - but I think at least once a day should ok (or on a config option) or I would also like to see a command to be able to trigger this check of active sectors on-chain manually.

**Comment by kernelogic** [comment]
Fixed in https://github.com/tech-greedy/singularity/pull/156/files#diff-f386da318050b201f01326db9255f6bbcbe5f3ab94491cca8d492b57c74414f7L257

Let's see if it happens again.
