### ISSUE TITLE
singularity-import is not compatbale with boost

### ISSUE THREAD

**Issue by marshyonline** [tech-greedy/singularity#167]
**Describe the bug**
the singularity-import command is not compatible with boost

**Version**
`2.0.0`

**To Reproduce**
Attempt to run the import tool against boost. 

**Expected behavior**
Deals import :D

**Comment by xinaxu** [comment]
@marshyonline The goal of singularity-import is to offer deal import automation for `lotus market node` which boost node is being stabilized. I expect all providers to eventually move to boost market which should have already solved the automation problem. If that's not the case, then we should move the topic to the boost slack channel and make a feature request for whatever is lacking.

**Comment by marshyonline** [comment]
The import tool is a great way to keep the flow importing deals smooth - 100% of my deals are offline deals, meaning i need to download the files and then import them.
This tool does exactly this for deals on the lotus-market node, but not if running boost.
Getting this tool todo the same thing, for legacy-deals and boost deals would be a great way to keep this constant.
The ability to manage concurrent download and import is great in this tool and i wouldn't like to use some hacked bash scripts todo the same

**Comment by xinaxu** [comment]
This should be an relatively simple change. The Boost API to import a deal is here
https://boost.filecoin.io/json-rpc-api#boostofflinedealwithdata
It is called in boost CLI here
https://github.com/filecoin-project/boost/blob/main/cmd/boostd/import_data.go#L74

**Comment by LaurenSpiegel** [comment]
Is this a change that needs to be made in boost or in singularity or both?

**Comment by marshyonline** [comment]
This is a change in the singularity-import tool to allow better and smarter offline deal imports.
Same as it does for the soon deprecated legacy-markets

**Comment by marshyonline** [comment]
Bumping this now that Legacy markets is EOL.
I think this can be flat our converted to import deals into Boost removing legacy markets support

**Comment by dirkmc** [comment]
boost exposes a libp2p API for making deal proposals (and for checking deal status):
https://boost.filecoin.io/boost-architecture/libp2p-protocols

Is there something else that would be needed by Singularity?

@marshyonline note that boost downloads deal data over HTTP, so if this is what you need to do you can probably now make online deals instead of offline deals.

**Comment by marshyonline** [comment]
Thanks, @dirkmc 
While Boost can do online deals with no problems, this tool has the use case where the car files were shipped to me on physical media and offline deals need to be imported. 
This tool manages the flow and concurrency of offline deals in a way that boost has no function todo.
Online deals also lack control from an SP side - I can stop offline deals instantly, but online deals require me to contact the sender to stop the flow. (shut boost down to kill 500x backlogged deal downloads if sent in bulk).

This is a great replacement for everyone's custom bash scripts - id love to see it built into boost in some way but for now I think we should like for like convert for boost.

**Comment by dirkmc** [comment]
@marshyonline thanks, that makes sense 👍 

It sounds like Singularity fills an important role that's different from boost so it probably makes sense for it to continue existing as a separate tool.
