### ISSUE TITLE
Amending files to a dataset

### ISSUE THREAD

**Issue by cryptowhizzard** [tech-greedy/singularity#88]
**Is your feature request related to a problem? 
no

**Additional context**
See subject. Amending files to a dataset that were downloaded in a later stage f.e..

**Comment by liuziba** [comment]
Can you elaborate what kind of situation and amendment

**Comment by cryptowhizzard** [comment]
When you have 50% of the dataset downloaded and want to start packing… you want to add the second after a few days

**Comment by liuziba** [comment]
How does it compare with creating a second preparation request with the 2nd part.

**Comment by cryptowhizzard** [comment]
Because then you need to abort downloads, ingestion and freeze the directory. That makes it complicated with tools like rsync when tou want to start download remaining to another dir

**Comment by cryptowhizzard** [comment]
Correct.

**Comment by liuziba** [comment]
With the latest enhancement, this can now achieved by
```shell
# This will pause scanning the folder. 
singularity prep pause scan <datasetName>
# This will continue scanning the folder from last point
singularity prep resume scan <datasetName>
```

**Comment by liuziba** [comment]
Closing since no further feedback is received.
